### ISSUE TITLE
Dropdown menu, next/prev entry buttons

### ISSUE THREAD

**Issue by lasalillo** [vvvv-dottore/Elementa#100]
It would be nice to have up and down buttons like in the "integer updown"

**Comment by sebescudie** [comment]
Nice one! Also make it react to mouse scroll like beta's enum IOBoxes?

**Comment by lasalillo** [comment]
that would be great!, and solves the problem when the entries count is too high

**Comment by sebescudie** [comment]
I wonder if we should come up with a ScrollableValue component that we could add to other widgets, this could also be handy for Value, Integer, Vectors...

**Comment by lasalillo** [comment]
ouuuh yeah

**Comment by sebescudie** [comment]
`ScrollableValue` will be released with 5.0.0.
