### ISSUE TITLE
Double Click doesn't work with Skia-Stride Renderer

### ISSUE THREAD

**Issue by lasalillo** [vvvv-dottore/Elementa#101]
I can't access to focusable mode while using Skia-Stride Renderer

**Comment by sebescudie** [comment]
This rather seems to be related to VL.Stride, as I cannot either get `IsMouseDoubleClick` to fire when double-clicking in a Stride SceneWindow. I'll open an issue there and update this one when we have feedback. Thanks for the report, did not see that one :)

**Comment by sebescudie** [comment]
Closing as this is fixed in gamma 2021.7!
