### ISSUE TITLE
AnyHovered should add mouse interaction

### ISSUE THREAD

**Issue by lasalillo** [vvvv-dottore/Elementa#102]
<img width="484" alt="VL Elementa Getters-AnyHovered_2020 10 18-20 16 33" src="https://user-images.githubusercontent.com/29660768/96376407-0a85ed00-117f-11eb-8527-0835692d81b1.png">

Does it make sense in this way? or is there a cleaner way to integrate this?
Maybe rename it to "On Interaction"

**Comment by sebescudie** [comment]
Hey Ari, thanks for this one. Indeed, `AnyHovered` will kinda flicker if your mouse goes over different widgets while editing. 

Though, adding this feature in `AnyHovered` feels weird to me : `AnyHovered` should not care if you're editing a widget or not. Instead, I've added an `AnyEditing` node (plus an help patch) to my branch, based on the same principle behind `AnyHovered` : if any widget of the graph is being edited (dragging, typing), the node will output `True`.

Does this help you in any way?

**Comment by lasalillo** [comment]
Cool, `AnyEditing` should be enough, thanks!

**Comment by sebescudie** [comment]
`AnyEditing` will be released with 5.0.0
