### ISSUE TITLE
Add mouse wheel interaction

### ISSUE THREAD

**Issue by simonemarin** [vvvv-dottore/Elementa#111]
Hallo, I added mouse wheel control to a Slider2D for finer control, a bit hackish as the Hover detection can return false positives, anyway I would submit that as a feature request as it seems natural to me to have mouse wheel control for Sliders, Rotary, etc

**Comment by sebescudie** [comment]
Hey simone, thanks for the feedback!

We have a `ScrollableValue` component already in the Experimental category that allows this behavior. It's not implemented in all the widgets though, but I think it's already there for `Slider`, `Value`, `Dropdown`, `Integer`, `IntegerUpDown`, `RadioGroup` and `Slider2D`.

There are two help patches dedicated to it :

- Modify a widget's value with the scrollwheel
- Change the default ScrollableValue key

Please shout here if you'd need it for another widget or if you have troubles using it.

**Comment by simonemarin** [comment]
ooook missed that, thank you. Looking into the ScrollableValueProcessorSettings black hole right now!
