### ISSUE TITLE
RadioGroup and its Buttons: Styles and Margins.

### ISSUE THREAD

**Issue by antongit** [vvvv-dottore/Elementa#23]
Here is a request for some features.

1.
Can I have please a style for the buttons in the RadioGroup?
For example, I would like to define Hover state for the Button and not for the RadioGroup itself?
Is it possible or missing at the moment?

2.
At the moment, when the button in the group is active, its Rect has some margin on all sides. Would be cool to be able to set it. In my scenario I would like to have it so big as the button itself, without any margin.

3. 
What about setting spacing between the buttons in the Group?

Related to:
#12

**Comment by natan-sinigaglia** [comment]
We still don't have Margins in the style, which is serious lack for proper styling.
You could have a look at the Style datatype, check what else is missing and report in a dedicated issue, so that we can make a plan....

**Comment by natan-sinigaglia** [comment]
regarding radioGroup, the buttons are defined by the Foreground properties of the style, so you can already target them with custom hovered style
