### ISSUE TITLE
How to Enable/Disable an Elementum

### ISSUE THREAD

**Issue by antongit** [vvvv-dottore/Elementa#24]
I would like to show a dropdown only on certain condition.
So I created a Switch right before ToSkiaLayer, but I get an error in the ComputeStyle. Maybe there should be an Empty Elementum which I can connect to the Switch or is there another solution to turn on/off Elementums?

**Comment by natan-sinigaglia** [comment]
![image](https://user-images.githubusercontent.com/6460926/63422248-4eaa2000-c40a-11e9-9427-3f8f9f3c0758.png)

if you do like that it works:
the empty pin of the switch must be of type IElementum

**Comment by antongit** [comment]
Cool, thank you!
