### ISSUE TITLE
How to manage styles locally?

### ISSUE THREAD

**Issue by sebescudie** [vvvv-dottore/Elementa#32]
The current way to create Style catalogs is too complex for simple usecases where you just want a few widgets and set a specific color for one of those.

- Should we add Color input pins to all widgets, as we have in Beta's UI elements? That would be cumbersome when creating new widgets.
- How to handle style overriding then?

**Comment by natan-sinigaglia** [comment]
write a node that procedurally generate style properties and delegates from the simple inputs (Background Color, Foreground color, Text Paint,...).
SetBasicStyle
