### ISSUE TITLE
How to provide a custom drawer for widgets?

### ISSUE THREAD

**Issue by sebescudie** [vvvv-dottore/Elementa#34]
Elementa provides the stream and the logic of the widgets, but how do we allow people to draw widgets themselves?

You could provide a drawer that implements for instance `IToggleDrawer`, and if it is `Assigned`, it overrides the default drawer.

Also now, the styles are computed inside the drawer : this does not make sense, it should be done by the manager so that the drawer is totally "stupid" and just draws stuff.

**Comment by natan-sinigaglia** [comment]
we could have a IElementumManager interface.
every widget manger implements it.
there's an IElementumDrawer interface that expects IElementumMangager as input and casts to widget specific manager
