### ISSUE TITLE
How to draw some simple text on top of the widgets (not next to it)?

### ISSUE THREAD

**Issue by sebescudie** [vvvv-dottore/Elementa#35]
We could think of two types of labels : one that gets considered by the Layout System (the one we have right now) and another one that just takes an offset from the widget it's linked to.

**Comment by sebescudie** [comment]
Still allow to snap the label to borders of the widget but don't take that into account in the Layouting system.

**Comment by natan-sinigaglia** [comment]
Done: OverlayLabel node
