### ISSUE TITLE
Step size for value properties

### ISSUE THREAD

**Issue by natan-sinigaglia** [vvvv-dottore/Elementa#42]
Eg. allows the slider widget to have step resolution (eg. 0.2) ( or 1 to step through integers)

**Comment by natan-sinigaglia** [comment]
Should this be part of the ValueProperty itself?
...going back to the topic of complexifying the ValueProperty or leaving the complexity into the editor.
connected also to Cycleable component I guess...

**Comment by sebescudie** [comment]
Solved with StepSize Component
