### ISSUE TITLE
TextField "Focus" Pin

### ISSUE THREAD

**Issue by jhnnslmk** [vvvv-dottore/Elementa#45]
Hey,
I came accross the use case (text overlay/prompt) where it would be ace to toggle the focus on the TextField from within the code to start typing to it right away.

On a second note I also noticed that Backspace deletes two characters at once

**Comment by natan-sinigaglia** [comment]
we can now trigger focus state from the patch. needs to be implemented in all the widgets.
implemented for integer and IntegerUpDown

**Comment by sebescudie** [comment]
there is now a focus pin on all widgets since 3.0.0
