### ISSUE TITLE
Error in 'How to Assign'

### ISSUE THREAD

**Issue by YanYas** [vvvv-dottore/Elementa#46]
Happy New Year! I came across this error while I was wandering through the docs. Using Gamma 2019.2.081 ![HowTo Assign Tasks-Application_2020 01 06-13 00 48](https://user-images.githubusercontent.com/9497052/71819761-d3799b80-3084-11ea-9c3e-64ed36ac3ab3.png)

**Comment by sebescudie** [comment]
Hello there, thanks for the report. 

Looks like there's a mixup between `Output` and `State Output` pin there, not sure where that comes from.  I pushed a fix to my branch, would like to understand where that comes from before merging though :/

**Comment by sebescudie** [comment]
Merged!
