### ISSUE TITLE
ScrollGroup (Bounds Spectral) builds from bottom rather than top

### ISSUE THREAD

**Issue by catvvvveasel** [vvvv-dottore/Elementa#48]
Seem odd that it starts at that bottom and adds controls upwards, I've tried to work out how to alter it, but have failed! I guess ideally the rectangle could be negative size to build the other way if you need it?

**Comment by sebescudie** [comment]
Hey Cat,

Thanks for the feedback ! Indeed, this one was fixed this weekend in my branch but not merged yet. Will land in master soon.

**Comment by catvvvveasel** [comment]
Great :) Thanks. I'm afraid I find the internals of elementa sheer black magic, so can't help out!

**Comment by sebescudie** [comment]
Hello again cat,

Just merged into master, new nuget should arrive soon!
