### ISSUE TITLE
Nested Layout patch broken in Beta

### ISSUE THREAD

**Issue by YanYas** [vvvv-dottore/Elementa#59]
Hi I tried VL.Elementa today and I came across the following issue:
![image](https://user-images.githubusercontent.com/9497052/80957578-b6bb5d80-8e03-11ea-83fa-78cc9a143d67.png)
I suspect there may be something missing from the current version of VL Beta that this library depends upon.

The error takes me down to Elementa.Core and here:

![image](https://user-images.githubusercontent.com/9497052/80957837-419c5800-8e04-11ea-86b8-54c14d507daf.png)

Of course this means I can't use the library for my project until the next update for vvvv, or rather that I'll have to switch back to the previous iteration until beta's vl gets updated, or is there some way I can fix this?

**Comment by natan-sinigaglia** [comment]
VL.Elementa should work from beta40 on
