### ISSUE TITLE
Maybe rename to VL.Skia.UIElements

### ISSUE THREAD

**Issue by tebjan** [vvvv-dottore/Elementa#6]
it is a specific implementation for skia and in the future there might be more ui element libraries for different frameworks, e.g. xenko or xamarin forms. 

using such a prominent name forces other repositories to choose different names and doesn't allow a non-framework specific library to exist in the VL namespace.

**Comment by natan-sinigaglia** [comment]
The way we structured the UIElements allows to keep separated the logic part from the drawer. this means that we could easily implement a xenko drawer without touching the logic (just providing device notifications from xenko engine).
So I would say this is a non specific library.
Maybe we could give it a more characteristic name, like UIElementa (from latin)  hihihi

**Comment by tebjan** [comment]
since current rework abstracts over drawing, i'm closing this. however, would be nice to also abstract over shape and hit-test to not be restricted to 2d space. then it can be called an interaction library.
