### ISSUE TITLE
Hide text on Color Widgets

### ISSUE THREAD

**Issue by jhnnslmk** [vvvv-dottore/Elementa#60]
It would be nice being able to hide the text on both ColorHSV and ColorRGB

**Comment by sebescudie** [comment]
such a thing can already be handled via Styles, see this screenshot :

![image](https://user-images.githubusercontent.com/8690430/82321719-98de2300-99d5-11ea-81ac-965cfe60b0a0.png)

**Comment by jhnnslmk** [comment]
Super, thanks.
