### ISSUE TITLE
Slider2D: typing feature

### ISSUE THREAD

**Issue by natan-sinigaglia** [vvvv-dottore/Elementa#8]
being able to type the components (needs to have more defined rectangles for components. i was thinking to put them side by side, one on left one on right; is you double click on left side of the slider you edit the X)

**Comment by sebescudie** [comment]
This is partially done in 42cac77ea72cf291290e2da40c2f63f95a47019b, for now components are still one on top of the other like in the previous version, but this will be updated soon.
