### ISSUE TITLE
Using several "PushToOverlay", don't behave as expected

### ISSUE THREAD

**Issue by lasalillo** [vvvv-dottore/Elementa#83]
<img width="1062" alt="HowTo Push widgets to overlay-Application_2020 07 02-18 25 17" src="https://user-images.githubusercontent.com/29660768/86385986-6b9db980-bc91-11ea-9aec-aca795b24ff0.png">

Only one overlay can be open, if i trigger the second one the first one closes and viceversa

**Comment by sebescudie** [comment]
New overlay system fixes this.
