### ISSUE TITLE
Text with background, not updated

### ISSUE THREAD

**Issue by lasalillo** [vvvv-dottore/Elementa#84]
Text with background widget, is only updated when it's hovered

**Comment by lasalillo** [comment]
Text widget (without bg) is not updated.

**Comment by sebescudie** [comment]
Also related : https://matrix.to/#/!ozhuuBcieNoMbRkvVj:matrix.org/$9KmWG7csm-kDvOIV2vXL4S2b1qr9HuVdshrsmy0e144
